import React from 'react';
import { Sparkles, ShieldCheck, Heart } from 'lucide-react';

const Footer = () => {
  return (
    <footer className="border-t border-slate-800/80 bg-dark-900/60 mt-auto">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
        <div className="flex flex-col md:flex-row items-center justify-between gap-6">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-tr from-brand-primary to-brand-secondary flex items-center justify-center shadow-md">
              <Sparkles className="w-4 h-4 text-white" />
            </div>
            <div>
              <p className="font-bold text-sm text-slate-200">AI-Powered Career Coach</p>
              <p className="text-xs text-slate-500">Autonomous Resume Engineering & AI Mock Interview Suite</p>
            </div>
          </div>

          <div className="flex flex-wrap items-center justify-center gap-6 text-xs text-slate-400">
            <span className="flex items-center gap-1.5">
              <ShieldCheck className="w-4 h-4 text-brand-success" />
              100% Client-Side Privacy & Token Security
            </span>
            <span>•</span>
            <span>Google Gemini AI Architecture</span>
            <span>•</span>
            <span>Mongoose & Node.js Engine</span>
          </div>
        </div>

        {/* ATS & Compatibility Disclaimer Requirement */}
        <div className="mt-8 pt-6 border-t border-slate-800/60 text-center">
          <p className="text-xs text-slate-400 max-w-3xl mx-auto leading-relaxed">
            <strong className="text-slate-300">Disclaimer:</strong> The compatibility, quality, and match scores generated by this platform are AI-based analytical estimates intended to help users optimize resumes and interview preparedness. Actual corporate Applicant Tracking Systems (ATS) and hiring teams employ varying proprietary algorithms and human evaluations.
          </p>
          <p className="text-[11px] text-slate-400 mt-4 flex items-center justify-center gap-1">
            Built with modern full-stack web engineering &pair; Pair programmed for production excellence.
          </p>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
